### ISSUE TITLE
Error in Moran Calculcation

### ISSUE THREAD

**Issue by Jerry-kiwi** [pysal/pysal#1014]
Pysal 1.14.3
Python 3.5
numpy 1.13.3
scipy 1.0.0
Ubuntu 16.04.3

I'me getting different results calculating local moran I using pysal anbd using geoda

python and pysal:
`import pysal as ps`
`qW = ps.weights.Queen.from_shapefile("SHAPES/R52_RAW.shp","LOC_KOD")`
`DATA=pd.read_csv('00_DATA.csv')`
`Y=DATA['w40'].values`
`lm = ps.esda.moran.Moran_Local(Y,qW,permutations=999)`
`pval=pd.DataFrame(lm.p_sim)`
`zval=pd.DataFrame(lm.q) `
`zval['Clust']='XXX'`
`#values indicate quandrant location 1 HH,  2 LH,  3 LL,  4 HL`
`zval['Clust'][zval[0]==1]='HH'`
`zval['Clust'][zval[0]==2]='LH'`
`zval['Clust'][zval[0]==3]='LL'`
`zval['Clust'][zval[0]==4]='HL'`
`zval['Clust'][pval[0]>0.05]='NS'`

[moran_w40_geoda](https://user-images.githubusercontent.com/8778463/33240289-f7f07b70-d2c4-11e7-90ec-fd3f16d7e08e.png)
[moran_w40_pysal](https://user-images.githubusercontent.com/8778463/33240290-fa7ccbfa-d2c4-11e7-8ad1-91d8d51d1c8c.png)

[SHAPES.zip](https://github.com/pysal/pysal/files/1503919/SHAPES.zip)

**Comment by ljwolf** [comment]
Hi,

The issue here is that your data is not aligned with your weights. 

If you look at the order of observations in the weights alongside the order in the csv:
```
DATA.LOC_KOD == qW.id_order
```
they're not the same. This is because your shapefile is in a different order than your csv. 

I'd suggest you either

# read both into data, join, and construct weights after join:
```python
import pysal as ps
import pandas as pd
shapes = ps.pdio.read_files('./R52_RAW.shp')
data = pd.read_csv('./00_DATA.csv')
full_data = shapes.merge(data, how='inner', on='LOC_KOD')
assert full_data.shape[0] == data.shape[0] # so none are lost
qW = ps.weights.Queen.from_dataframe(full_data, idVariable='LOC_KOD')
assert (full_data.LOC_KOD == qW.id_order).all()
# do the rest of analysis with full_data
```
# Re-sort the data according to the weights order
starting from your sample:
```python
DATA['weights_order'] = DATA.LOC_KOD.apply(lambda x: qW.id_order.index(x))
DATA = DATA.sort_values("weights_order")
assert (DATA.LOC_KOD == qW.id_order).all()
```

I tried the first & mapped the result, and see nearly the same as GeoDa, with one switching on and one switching off. 
![aout](https://user-images.githubusercontent.com/2250995/33241632-30ba32d4-d2c0-11e7-9b77-52f0604dc942.png)
