### ISSUE TITLE
local_moran

### ISSUE THREAD

**Issue by Morenagl** [pysal/pysal#1140]
hello guys, I have a problem with local maran, I have calculated my weight matrix and  neighbors, then the sparse matrix, but when I use it with an array variable it gives an error  which that I made a mistake in my W 

![p0](https://user-images.githubusercontent.com/53742915/62862609-993ee480-bd06-11e9-9a40-1674a0489443.PN
![p1](https://user-images.githubusercontent.com/53742915/62862631-b2479580-bd06-11e9-8cac-0a4d0ceef379.PNG)
![p2](https://user-images.githubusercontent.com/53742915/62862632-b2479580-bd06-11e9-9ebd-a2b4008250fc.PNG)
![p3](https://user-images.githubusercontent.com/53742915/62862634-b2e02c00-bd06-11e9-939e-f3d819d73175.PNG)
![p4](https://user-images.githubusercontent.com/53742915/62862635-b2e02c00-bd06-11e9-8246-047745cea9ce.PNG)
![p5](https://user-images.githubusercontent.com/53742915/62862636-b2e02c00-bd06-11e9-8fd0-8435fb093ac4.PNG)
![p6](https://user-images.githubusercontent.com/53742915/62862637-b2e02c00-bd06-11e9-957d-18fe9003a868.PNG)

@joshk  @sjsrey  @denadai2 @darribas  @ljwolf  i don' know where is the problem in my code 
thank you for help

**Comment by ljwolf** [comment]
Hey @Morenagl, like I suggested earlier, I **really think you should** do something easier:
1. Use something that assists you to build your weights, rather than building the W manually. Say, you have an `(N,2)` array of `coordinates`. This'd look something like:
```python
from sklearn.metrics.pairwise import haversine_distances
from pysal.lib import weights
distances = haversine_distances(cordinates)
my_weights = weights.full2W(distances)
```
2. use the built-in `DistanceBand` weights builder, probably something like `libpysal.weights.DistanceBand(coordinates, threshold=numpy.inf, binary=False, alpha=1)`

That said, this [does appear to be a bug](https://github.com/pysal/esda/issues/86), @pysal/devs, since we assume that no one would send self-neighbors to the local statistics. The conditional randomization chokes. Repro in the linked issue.

**Comment by Morenagl** [comment]
@ljwolf  thank you so much, I didn't use the earlier distance because it was euclidien, I didn't know that there is a function in python does that work without code it manually 
thank you

**Comment by ljwolf** [comment]
Hmm... if you build an Arc-based KDTree, it should work ok:
```python
kdt = cg.KDTree(coordinates, distance_metric='Arc')
weights.DistanceBand(kdt, threshold=numpy.inf, binary=False, alpha=1)
```
Not sure about the specifics of your data. Anyway, definitely try the alternative method.

If you do intend to make weights objects manually, it's usually a good idea to *omit* zero-weight connections unless they're actually meaningful links.

**Comment by Morenagl** [comment]
@ljwolf  thank you for all these answer i have resoluted my problem using haversine function and it works
