### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by chivasblue** [pysal/pysal#548]
I am trying to install on Ubntu 14.04 with python3, however I am running into below error while installation.
***************
Collecting pysal
  Using cached PySAL-1.8.0.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-ny96vzc7/pysal/setup.py", line 16, in <module>
        from pysal.version import version as dversion
      File "/tmp/pip-build-ny96vzc7/pysal/pysal/__init__.py", line 38, in <module>
        import pysal.cg
      File "/tmp/pip-build-ny96vzc7/pysal/pysal/cg/__init__.py", line 4, in <module>
        from shapes import *
    ImportError: No module named 'shapes'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "/tmp/pip-build-ny96vzc7/pysal/setup.py", line 16, in <module>

        from pysal.version import version as dversion

      File "/tmp/pip-build-ny96vzc7/pysal/pysal/__init__.py", line 38, in <module>

        import pysal.cg

      File "/tmp/pip-build-ny96vzc7/pysal/pysal/cg/__init__.py", line 4, in <module>

        from shapes import *

    ImportError: No module named 'shapes'

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ny96vzc7/pysal
*************

Below are the python packages I have installed:
****************
postgres@ubuntu:~$ sudo -H pip3 list
command-not-found (0.3)
decorator (3.4.0)
numpy (1.9.1)
pip (6.0.6)
psycopg2 (2.5.4)
pycurl (7.19.3)
pygobject (3.12.0)
pymongo (2.7.2)
pyshp (1.2.1)
python-apt (0.9.3.5)
scipy (0.13.3)
setuptools (3.3)
six (1.5.2)
SShapes (1.0.0)
ufw (0.34-rc-0ubuntu2)
unattended-upgrades (0.1)
postgres@ubuntu:~$
**********

I read on some older threads on google that pysal does not support python 3.x, is that still the case?

Thanks!

**Comment by chivasblue** [comment]
Ok, got from here http://pysal.readthedocs.org/en/latest/users/installation.html that it needs python 2.6 or 2.7, closing the issue, however any chances of release on python 3 anytime soon?

Thanks!

**Comment by sjsrey** [comment]
We have been working on a 3.0 port. Hopefully this year (2015) it will be done.

**Comment by shongololo** [comment]
+1 for Python 3.

**Comment by joehand** [comment]
+1 for Python 3. Is the port on GitHub?

**Comment by ljwolf** [comment]
@joehand the current port is [here](https://github.com/ljwolf/pysal/tree/py3conv), but it's not done yet. 

You can try doing a [pip install from a github branch](http://stackoverflow.com/questions/20101834/pip-install-from-github-repo-branch), but I'd recommend cloning the repository, running the `mk3` script in the git root, and using it from there. Since it's still in development, packaging isn't smooth yet. 

Right now, we are [closer than ever](https://github.com/pysal/pysal/wiki/Converting-2-to-3-Notes#not-fileio) to it being done, but core functionality of the regression module still does not work in python 3.
