### ISSUE TITLE
Polygon.contains_point does not correctly process multipart polygons.

### ISSUE THREAD

**Issue by schmidtc** [pysal/pysal#603]
See http://gis.stackexchange.com/questions/130493/why-is-shapely-and-contains-point-not-detecting-point-being-on-land

The bug deals with using the vertices property which flattens all parts into a single array. The method is drawing line segments between the endpoints of the multiple parts. See the attached image.

![polygoncontainspoint](https://cloud.githubusercontent.com/assets/1403099/6838300/52273416-d32d-11e4-9882-3d3dfc5f0d3d.png)

It looks like @sjsrey implemented the original method. Note, the standalone get_polygon_point_intersect method appears to work correctly. I never liked the vertices property, it should be deprecated.

**Comment by sjsrey** [comment]
We used the vertices property for some of the contiguity builders so I don't think we should completely get rid of that property. We shouldn't, however, be using it for p-in-p tests or for drawing.

On a related note, we probably should add a MultiPolygon class so we interface with other standards  (beyond shapefiles) more fully.

One approach would be to move the point-in method into the Ring class. A Polygon point-in method would dispatch a call to each of its rings point-in method - stopping as soon one of its Rings returns True. Otherwise the Polygon point-in method returns False.

For MultiPolygon, its point-in method would dispatch to its Polygons which in turn call on down to their Rings point-in methods.

Food for thought.
