### ISSUE TITLE
Testing on OSX

### ISSUE THREAD

**Issue by ljwolf** [pysal/pysal#709]
Now that we're not using `apt-get` in Travis, it might be a good idea to enable OSX in travis testing. 
It should be a simple fix, adding `- osx` under `- linux` in the `os` category.

**Comment by ljwolf** [comment]
Huh, not a productive avenue, since there is [Travis OSX is pretty hard to wrangle for python projects](https://github.com/travis-ci/travis-ci/issues/1765). no `virtualenv` on their OSX images, and that's the very first thing executed by most install scripts. Some have gotten this working, but it looks very hacky. 

Lame that this works out of the box in other languages (Julia, Go) but not in python...

**Comment by ljwolf** [comment]
Of note, though, is their suggestion in documentation of the [environment variables](http://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables) not to rely on `HOME=/home/travis`

We rely on it to set `PATH` to use miniconda. We might want to call to `pwd` for the current directory, and install anaconda into a known place using something like `-p ./miniconda`.

**Comment by sudoankit** [comment]
I can work on this. 
I have done some previous work to enable a python build on Travis.

A good approach already noted by @ljwolf is installation of Anaconda distribution or (miniconda) on a travis machine, and if required install packages using homebrew.

Some resources which were helpful are [conda docs](http://conda.pydata.org/docs/travis.html) and [a particular stack exchange question](http://stackoverflow.com/questions/29587581/how-to-build-macosx-executables-on-travis-ci)

I will report if any problems arise for guidance.

**Comment by jlaura** [comment]
A few note that might be helpful:

1. I would be cautious using homebrew as the dependencies are placed into /usr/local and, if we ever want to do #2, this could be a problem (if pandas were a dependency for example).  The alternative is to use the `requirements` and `run` tags in the meta.yaml file to specify the dependencies.
2. Recently, I have been playing around with binstar to serve dependencies (GDAL, OpenCV, Boost, etc.) to python packages that are not pip installable.  [Here] (https://github.com/USGS-Astrogeology/conda-gdal) is a link to an example where an OSX and Linux build of GDAL are created using TravisCI.  The resultant packages are then uploaded to my binstar so that anyone can do a `conda install gdal -c jlaura`.

If this looks appealing, I can offer assistance with any setup questions.

P.S. The GDAL build is not 100% stable yet, OpenCV is, but the GDAL one is maybe closer to what PySAL would be.

**Comment by jGaboardi** [comment]
Testing with OS X will be resolved in #1179
