### ISSUE TITLE
`min_threshold_dist_from_shapefile` creating an island in some cases

### ISSUE THREAD

**Issue by darribas** [pysal/pysal#716]
I've found it working with a different dataset, but I've been able to replicate the issue with one of the example datasets:

```python
import pysal as ps
clb = ps.examples.get_path('baltim.shp')
mt = ps.min_threshold_dist_from_shapefile(clb)
w_clb = ps.threshold_continuousW_from_shapefile(clb, mt)
```

Returns:

```
WARNING: there is one disconnected observation (no neighbors)
Island id:  [101]
```

Adding a small amount to the threshold seems to solve the problem:

```python
w_clb = ps.threshold_continuousW_from_shapefile(clb, mt+mt*0.0000001)
```

Does not return any warning.

I think this is probably just that the point is at exactly the same distance hence it doesn't pick it up as within. But I'm just curious why it'd throw the warning with some data, not with others.

**Comment by sjsrey** [comment]
The island warning works as it should: when isolates are detected the warning gets fired.

Now, the reason there are isolates in this case could be a precision issue so that in some cases the "exactly" part doesn't hold under the hood. The general logic is to find the maximum nn distance (by querying a kd tree). Then use that distance on the same tree to find all pairs within that distance by calling the trees `sparse_distance_matrix` method. Its docs say:

```
sparse_distance_matrix(self, max_distance, p)

Compute a sparse distance matrix

Computes a distance matrix between two KDTrees, leaving as zero
any distance greater than max_distance.
```

So this might be more fragile than we would like.

**Comment by darribas** [comment]
Right, that was my hunch a precision issue. In any case I've run into, adding a marginal amount to the threshold (e.g. threshold = threshold + threshold * 0.0000001) solves the problem.
