### ISSUE TITLE
Object-oriented design for viz module

### ISSUE THREAD

**Issue by pdoongarwal** [pysal/pysal#761]
The modules under [contrib](https://github.com/pysal/pysal/tree/master/pysal/contrib) are not implemented in classes. I understand that they are still under development phase, but before making any contrib module a core module, we are going implement classes in them anyway.

It would be convenient in terms of testing to implement them in classes rather than functions from the development phase itself.

**Comment by sjsrey** [comment]
Is this specific to a particular contrib module? Otherwise this is too vague to address.

**Comment by pdoongarwal** [comment]
Yes, viz module to be specific.

**Comment by pdoongarwal** [comment]
@sjsrey Should I make the changes and send a PR?

**Comment by darribas** [comment]
What would be the benefits of turning methods into classes?

**Comment by pdoongarwal** [comment]
Only classes can be inherited not functions.
If certain functions are to be used in other functions then they need to be re-written.

**Comment by jlaura** [comment]
Specifically in response to the last post - I would have a look at:
http://programmers.stackexchange.com/questions/134097/why-should-i-prefer-composition-over-inheritance.
In short, you are going to be hard pressed to find a Python package that is
written in a purely OO style because Python is not Java.



On Mon, Apr 4, 2016 at 9:57 PM, Prabhat Doongarwal <notifications@github.com
