### ISSUE TITLE
viz: folium_mapping.ipynb AttributeError: 'Map' object has no attribute '_build_map'

### ISSUE THREAD

**Issue by sjsrey** [pysal/pysal#762]
Not sure if this broke with the 2-3 port or ?

Cell [11] is the culprit

**Comment by ljwolf** [comment]
huh, yes I see. I think this is actually a change in Folium since when I built the tool. 

I was just getting the raw HTML/JS and then displaying it in an IPython iframe. Now, I guess they've removed `_build_map()` from Folium objects, meaning you can't embed them the way I was doing. 

Will look into fixes.

**Comment by ljwolf** [comment]
As noted in the pull, I've [submitted a fix](https://github.com/pdoongarwal/pysal/pull/1) to @pdoongarwal that, if merged, will update #759 with the correct folium code.

**Comment by ljwolf** [comment]
Hmm... now I can't figure out why my branch is incompatible. Should I submit both of our commits separately?

**Comment by pdoongarwal** [comment]
@ljwolf Yes, that seems the only way.

**Comment by ljwolf** [comment]
closed by #764
