### ISSUE TITLE
Windows 7, 64 bit installation issue with visual C++ for python

### ISSUE THREAD

**Issue by h-krishna** [pysal/pysal#769]
Hi,
   I am in  a win7 64 env and the pip installation failed repeatedly. The error thrown is : command 'C:\Users\xxxxxxxx\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\bin\cl.exe"' failed with exit status 2. Pretty sure it is linked to some dependency. Not sure which one. I have numpy --> 1.10.4, scipy-->0.17 and python 2.7
Regards
Hari

**Comment by ljwolf** [comment]
Can you verify that numpy/scipy are already installed? I know you [cannot](https://github.com/numpy/numpy/issues/5479) `pip install numpy` successfully on windows by default right now, so if our `pip install` fails because numpy's fails, then this is an upstream issue. 

Have you tried this using Anaconda or Enthought canopy?

**Comment by ljwolf** [comment]
Closing, failure to replicate.
