### ISSUE TITLE
Coverage tests lines in `__main__`. 

### ISSUE THREAD

**Issue by ljwolf** [pysal/pysal#845]
We should probably not consider the code contained below `if __name__ == '__main__'` blocks in our coverage statistics. 

If you [look at coveralls](https://coveralls.io/jobs/16444253/source_files/954095238#L452), this might actually reflect a large part of the current uncovered code.

**Comment by kris-singh** [comment]
@ljwolf any ideas how this is done.

**Comment by ljwolf** [comment]
This [provides directions](http://coverage.readthedocs.io/en/latest/excluding.html), and could be done using either the in-line pragma or with a package-wide command, I think.

**Comment by djokester** [comment]
What is the status of this Issue? Is it still open?

The code in [/pysal/pysal/cg/sphere.py](https://github.com/pysal/pysal/blob/master/pysal/cg/sphere.py) doesn't match the one given in [Coveralls](https://coveralls.io/jobs/16444253/source_files/954095238#L452)

Rather than using `#pragma: no cover` to exclude the code below `if __name__ == '__main__'` it seems that the code segment has been deleted entirely. So is this issue still open for a Pull Request ?

**Comment by sugam45** [comment]
hi @ljwolf.  I just wanted to know if this issue is already taken?
if not then would like to work upon this issue.
