### ISSUE TITLE
SpInt may cause -inf in input data

### ISSUE THREAD

**Issue by jtsmn** [pysal/pysal#867]
@@##Thank you for filing this issue! To help troubleshoot this issue, please follow
the following directions to the best of your ability before submitting an issue.
Feel free to delete this text once you've filled out the relevant requests. 

Please include the output of the following in your issue submission. If you don't know how to provide the information, commands to get the relevant information from the Python interpreter will follow each bullet point.

Feel free to delete the commands after you've filled out each bullet. 
- Platform information:

```
posix.uname_result(sysname='Darwin', nodename='innsbruck-umh.cs.umn.edu', release='15.5.0', version='Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64', machine='x86_64')
```
- Python version: 

```
3.4.4 (default, Mar  2 2016, 03:31:27) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
```
- SciPy version:

```
0.17.0
```
- NumPy version:

```
1.10.4
```

In the new `spint` implementation on the dev branch, running any model with `cost_func='pow'` will lead to 0s being `-inf`, because the cost_function is set to `np.log` (see `__init()__` in BaseGravity, https://github.com/pysal/pysal/blob/dev/pysal/contrib/spint/gravity.py#L166).

One approach is to use `np.log1p`, which is what is done in the example `.ipynb`

**Comment by sjsrey** [comment]
This seems to be a special case of "self-neighbor". Numerical fixes are possible, but the substantive issues are a bit thornier, so leaving this open.

**Comment by TaylorOshan** [comment]
Hmm, I'm not sure what the best default behavior should be. The error is being thrown because in the Poisson spatial interaction model you still need to log the covariates, and if you have covariates with a value of zero then you will be in trouble. As @jtsmn mentioned one way around it would be to add 1 to values of zero, which is the same as using `np.log1p`, thought I am not aware of any research that looks to see how this ultimately effects the model. It has, however, been shown that adding a small constant to values of zero for the dependent variable can impact the model, so I would assume this is also the case for adding constants to covariates. 

 In most applications I think there is usually an abundance of data to describe origin and destination locations that do not have any zeros, so this has not generally been a problem. For instance, if you are looking at migration between census tracts or counties, and you were using population as a proxy for origin/destination variables, then it would not make sense for there to be migrations from `a` to `b` if there was zero population in `b`, and so I don't think the issue of zero covariate values has popped up using traditional aggregate datasets, especially for simpler models with fewer covariates. 

Thinking maybe the most flexible solution would be to raise an informative error?

**Comment by sjsrey** [comment]
+1 on raising an informative error

**Comment by TaylorOshan** [comment]
This was handled in #875.
