### ISSUE TITLE
Can't read ESRI spatial weights matrix

### ISSUE THREAD

**Issue by fiftysevendegreesofrad** [pysal/pysal#937]
Code I tried:
```
    import pysal
    arcgis_swm = pysal.open('swm.swm','r')
    connectivity = arcgis_swm.read()
    arcgis_swm.close()
```
This happens:
```
  File "test.py", line 13, in <module>
    connectivity = arcgis_swm.read()
  File "C:\Users\Crispin\Anaconda2\lib\site-packages\pysal\core\IOHandlers\arcgi
s_swm.py", line 69, in read
    return self._read()
  File "C:\Users\Crispin\Anaconda2\lib\site-packages\pysal\core\IOHandlers\arcgi
s_swm.py", line 111, in _read
    id_var, srs = header01[:-1].split(';')
ValueError: too many values to unpack
```
Will attach offending file swm.swm which has come straight from ArcMap 10.3
[swm.zip](https://github.com/pysal/pysal/files/943720/swm.zip)

'2.7.13 |Anaconda 4.3.1 (64-bit)| (default, Dec 19 2016, 13:29:36) [MSC v.1500 6
4 bit (AMD64)]'

Scipy 0.18.1

Numpy 1.11.3

**Comment by ljwolf** [comment]
I can reproduce this bug with version `1.13`, as well as version `1.5`.

**Comment by ljwolf** [comment]
I think this may be due to a change in the swm file format, since we can still read `ohio.swm` just fine:
```python
import pysal as ps
ps.open(ps.examples.get_path('ohio.swm')).read()
```

**Comment by sjsrey** [comment]
I think the swm file format may have changed:

```
>>> f = open('/home/serge/Dropbox/p/pysal/users/swm/swm.swm')
>>> header01 = f.readline()
>>> header01
'VERSION@10.1;UNIQUEID@FID_1;SPATIALREFNAME@OSGB_1936_British_National_Grid;INPUTFC@D:\\boundary mapping\\pysal\\nrs_exp_gen.shp;WTYPE@4;DISTANCEMETHOD@EUCLIDEAN;EXPONENT@#;THRESHOLD@#;NUMNEIGHS@0;INPUTTABLE@#;TIMEFIELD@#;TIMETYPE@#;TIMEVALUE@#;INPUTNET@#;IMPEDANCEFIELD@#;BARRIERFC@#;UTURNPOLICY@#;RESTRICTIONS@#;USEHIERARCHY@#;SEARCHTOLERANCE@#;ADDCONCEPT@#;FIXEDWEIGHTS@True\n'
>>> f2 = open(ps.examples.get_path('ohio.swm'))
>>> header02 = f2.readline()
>>> header02
'RECORD_ID;Unknown\n'
```

**Comment by mjanikas** [comment]
We have not changed the format of the SWM file in quite a while.  I will take a look and get back to you.

**Comment by mjanikas** [comment]
I will contact Sergio Rey directly to help you resolve the issue.

**Comment by shaohu** [comment]
The PR for fixing this bug is made. Please see #942 
Yes, the version of .swm files changed after [10.1](http://desktop.arcgis.com/en/arcmap/10.3/tools/spatial-statistics-toolbox/generate-spatial-weights-matrix.htm). In terms of the file header and how the weights are organized. More parameters about how a .swm file is generated are contained in the header. Below are some parameter examples:
- VERSION@10.1
- UNIQUEID@CONID
- SPATIALREFNAME@GCS_WGS_1984
- INPUTFC@C:/git/test/ne_10m_admin_0_countries/ne_10m_admin_0_countries.shp
- WTYPE@4
- DISTANCEMETHOD@EUCLIDEAN
- EXPONENT@#
- THRESHOLD@#
- NUMNEIGHS@0
- INPUTTABLE@#
- TIMEFIELD@#
- TIMETYPE@#
- TIMEVALUE@#
- INPUTNET@#
- IMPEDANCEFIELD@#
- BARRIERFC@#
- UTURNPOLICY@#
- RESTRICTIONS@#
- USEHIERARCHY@#
- SEARCHTOLERANCE@#
- ADDCONCEPT@#
- FIXEDWEIGHTS@True
- HASZ@False


Now the reader could firstly parse the header of the file and determine its version. Then read the file correctly.

I also plan to reconstruct the [writer function](https://github.com/shaohu/pysal/blob/dev/pysal/core/IOHandlers/arcgis_swm.py#L197) so PySAL could write the .swm files in the new version. In order to do that, when the first time reading the .swm file, parameter information in the header should be reserved somewhere, and be reused for next time writing. I find a similar function [here](https://github.com/shaohu/pysal/blob/dev/pysal/weights/weights.py#L1021). I think I can write another function to **directly preserve the parameter information inside of the Weight class** as well, since they are also useful for the weight class. Let me know what you think. @ljwolf @sjsrey @mjanikas
