### ISSUE TITLE
Estimate panel models in spreg

### ISSUE THREAD

**Issue by karldw** [pysal/pysal#958]
As @lanselin mentioned in #949 and [PEP 0007](https://github.com/pysal/pysal/blob/952ea04029165048a774d9a1846cf86ad000c096/doc/source/developers/pep/pep-0007.rst), work is in progress on spatial panel models.

It would love to see panel models included, and I'd be happy to help contribute.  What steps are necessary to get there?
(The most obvious to me is calculating HAC errors that take into account temporal correlation, but I'm sure there are many others.)

**Comment by lanselin** [comment]
Note that the current spreg module in pysal is frozen, since future development has moved to a separate github site and is run through the center for spatial data science at uchicago. The specifics of integrating this with future releases of PySal still need to be worked out, but it's important to know that none of the new work is reflected in the current version that is on the PySal github repo. I'd be happy to take this up off-line at anselin@uchicago.edu.

**Comment by ljwolf** [comment]
Just to be sure, I'd love to help get spatial panel in as well. I've been looking at some Bayesian strategies based on some previous code I worked on.

Not sure what the state is there, but I'm definitely interested and able to help as a maintainer of pysal and dev familiar with the math and methods.
