### ISSUE TITLE
base_lisa_cluster function call does not pass p_thresh

### ISSUE THREAD

**Issue by pattyf** [pysal/pysal#971]
The calling function plot_lisa_cluster(shp_link, lisa, p_thres=0.01...) in mapping.py does not not pass the p_thres argument to 
 base_lisa_cluster(lisa_obj, lisa) function call on line 1100

I think it should be:
base_lisa_cluster(lisa_obj, lisa, p_thres)

https://github.com/pysal/pysal/blob/1e254a023ca40949ce7c6f52421726495958f71e/pysal/contrib/viz/mapping.py#L1100

**Comment by darribas** [comment]
Thanks very much for the issue @pattyf. You're exactly right, that's a bug. Happy to accept a PR on that, or I can try to get to this next week otherwise.

Also, note that we're moving our plotting API to one that looks more like GeoPandas so it integrates better with the rest of the stack. For an example of how this could work, you can have a look at:

https://gist.github.com/darribas/691ad184280590d1219ffcf9a1678030

Thanks again for reporting!

**Comment by darribas** [comment]
I've made a small PR with a fix for this. Thank you very much for reporting again @pattyf!!!
